spring:
    application:
        name: goout-backend
    # threads.virtual.enabled: true
    threads:
        virtual:
            enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"

